name: CI/CD - FlowSense API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (Install & Smoke)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Smoke test (/health)
        env:
          DISABLE_AUTH: 'true'
          PORT: '3000'
        run: |
          set -e
          node server.mjs & SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          # Warte bis der Server antwortet (max. 10s)
          for i in {1..20}; do
            if curl -sf http://localhost:3000/health >/dev/null; then
              curl -sf http://localhost:3000/health | tee health.json
              exit 0
            fi
            sleep 0.5
          done
          echo "Server did not become healthy in time"; exit 1

      - name: Upload smoke test artifact
        uses: actions/upload-artifact@v4
        with:
          name: health-response
          path: health.json

  cd:
    name: CD (Cloud Foundry Deploy)
    needs: ci
    # Nur auf main UND nur wenn alle CF-Secrets existieren
    if: ${{ github.ref == 'refs/heads/main' && secrets.CF_API != '' && secrets.CF_USERNAME != '' && secrets.CF_PASSWORD != '' && secrets.CF_ORG != '' && secrets.CF_SPACE != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Stabiler: offizielles CF-CLI Action-Login statt apt-key/apt
      - name: CF CLI Login
        uses: cloudfoundry/cf-cli-action@v2
        with:
          cf_api:   ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}
          # skip_ssl_validation: true # nur falls nötig

      - name: Push to Cloud Foundry
        env:
          NODE_ENV: production
        run: cf push -f manifest.yml

      - name: Post-deploy health check
        env:
          APP_NAME: flowsense-api
        run: |
          set -e
          # erstes Route-Label nach "routes:" auslesen
          ROUTE=$(cf app "$APP_NAME" | awk '/routes:/{getline; print $1; exit}')
          echo "Route: $ROUTE"
          for i in {1..30}; do
            if curl -sf "https://$ROUTE/health" | tee cf-health.json; then
              exit 0
            fi
            sleep 2
          done
          echo "App not healthy yet"; exit 1

      - name: Upload CF health artifact
        uses: actions/upload-artifact@v4
        with:
          name: cf-health-response
          path: cf-health.json
