name: CI/CD - FlowSense API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (Install & Smoke)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps (retry)
        run: |
          node -v
          npm -v
          for i in 1 2 3; do
            npm ci --no-audit --no-fund && break
            echo "npm ci failed (attempt $i). Retrying in 10s..."
            sleep 10
          done

      - name: Smoke test (/health, robust)
        env:
          DISABLE_AUTH: 'true'
          PORT: '3000'
        run: |
          set -euxo pipefail
          node server.mjs & SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          for i in {1..30}; do
            if curl -sf http://localhost:3000/health >/dev/null; then
              curl -sf http://localhost:3000/health | tee health.json
              exit 0
            fi
            sleep 0.5
          done
          echo "Server did not become healthy in time"; exit 1

      - uses: actions/upload-artifact@v4
        with:
          name: health-response
          path: health.json

  cd:
    name: CD (Cloud Foundry Deploy)
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy (no CF secrets configured)
        if: ${{ !(secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE) }}
        run: echo "Skipping CD: CF secrets missing."

      - uses: actions/checkout@v4
        if: ${{ secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE }}

      - name: CF CLI Login
        if: ${{ secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE }}
        uses: cloudfoundry/cf-cli-action@v2
        with:
          cf_api:   ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}

      - name: Push to Cloud Foundry
        if: ${{ secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE }}
        env:
          NODE_ENV: production
        run: cf push -f manifest.yml

      - name: Post-deploy health check
        if: ${{ secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE }}
        env:
          APP_NAME: flowsense-api
        run: |
          set -e
          ROUTE=$(cf app "$APP_NAME" | awk '/routes:/{getline; print $1; exit}')
          echo "Route: $ROUTE"
          for i in {1..30}; do
            if curl -sf "https://$ROUTE/health" | tee cf-health.json; then
              exit 0
            fi
            sleep 2
          done
          echo "App not healthy yet"; exit 1

      - uses: actions/upload-artifact@v4
        if: ${{ secrets.CF_API && secrets.CF_USERNAME && secrets.CF_PASSWORD && secrets.CF_ORG && secrets.CF_SPACE }}
        with:
          name: cf-health-response
          path: cf-health.json

