name: CI/CD - FlowSense API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (Lint/Install/Smoke Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Placeholder for lint/tests if you add them later
      - name: Lint (skipped - no linter configured)
        run: echo "No lint step configured yet."

      - name: Smoke test (start server & hit /health)
        env:
          DISABLE_AUTH: 'true'
          OPENAI_API_KEY: '${{ secrets.OPENAI_API_KEY || '' }}'
          PORT: '3000'
        run: |
          node server.mjs &
          SERVER_PID=$!
          echo "Server PID: $SERVER_PID"
          sleep 2
          curl -sf http://localhost:3000/health | tee health.json
          kill $SERVER_PID

      - name: Upload smoke test artifact
        uses: actions/upload-artifact@v4
        with:
          name: health-response
          path: health.json

  cd:
    name: CD (Cloud Foundry Deploy)
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install CF CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb http://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update -y
          sudo apt-get install -y cf8-cli || sudo apt-get install -y cf-cli

      - name: CF Login
        env:
          CF_API: ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_SPACE: ${{ secrets.CF_SPACE }}
        run: |
          cf api "$CF_API"
          cf auth "$CF_USERNAME" "$CF_PASSWORD"
          cf target -o "$CF_ORG" -s "$CF_SPACE"

      - name: Push to Cloud Foundry
        env:
          NODE_ENV: production
        run: |
          cf push -f manifest.yml

      - name: Post-deploy health check
        env:
          APP_NAME: flowsense-api
        run: |
          APP_ROUTE=$(cf app "$APP_NAME" | awk '/routes:/ {print $2}')
          echo "Route: $APP_ROUTE"
          sleep 5
          curl -sf "https://$APP_ROUTE/health" | tee cf-health.json

      - name: Upload CF health artifact
        uses: actions/upload-artifact@v4
        with:
          name: cf-health-response
          path: cf-health.json
