name: CI/CD - FlowSense API

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (Install & Smoke)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install deps (retry)
        run: |
          node -v
          npm -v
          for i in 1 2 3; do
            npm ci --no-audit --no-fund && break
            echo "npm ci failed (attempt $i). Retrying in 10s..."
            sleep 10
          done

      - name: Smoke test (/health, robust)
        env:
          DISABLE_AUTH: 'true'
          PORT: '3000'
        run: |
          set -euxo pipefail
          node server.mjs & SERVER_PID=$!
          trap "kill $SERVER_PID" EXIT
          for i in {1..30}; do
            if curl -sf http://localhost:3000/health >/dev/null; then
              curl -sf http://localhost:3000/health | tee health.json
              exit 0
            fi
            sleep 0.5
          done
          echo "Server did not become healthy in time"; exit 1

      - name: Upload smoke test artifact
        uses: actions/upload-artifact@v4
        with:
          name: health-response
          path: health.json

  cd:
    name: CD (Cloud Foundry Deploy)
    needs: ci
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Gate: check CF secrets
        id: gate
        env:
          CF_API:      ${{ secrets.CF_API }}
          CF_USERNAME: ${{ secrets.CF_USERNAME }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_ORG:      ${{ secrets.CF_ORG }}
          CF_SPACE:    ${{ secrets.CF_SPACE }}
        run: |
          set -e
          if [ -n "$CF_API" ] && [ -n "$CF_USERNAME" ] && [ -n "$CF_PASSWORD" ] && [ -n "$CF_ORG" ] && [ -n "$CF_SPACE" ]; then
            echo "deploy=true" >> "$GITHUB_OUTPUT"
          else
            echo "deploy=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Skip deploy (no CF secrets configured)
        if: steps.gate.outputs.deploy != 'true'
        run: echo "Skipping CD: CF secrets missing."

      - name: Checkout
        if: steps.gate.outputs.deploy == 'true'
        uses: actions/checkout@v4

      - name: CF CLI Login
        if: steps.gate.outputs.deploy == 'true'
        uses: cloudfoundry/cf-cli-action@v2
        with:
          cf_api:   ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          org:      ${{ secrets.CF_ORG }}
          space:    ${{ secrets.CF_SPACE }}

      - name: Push to Cloud Foundry
        if: steps.gate.outputs.deploy == 'true'
        env:
          NODE_ENV: production
        run: cf push -f manifest.yml

      - name: Post-deploy health check
        if: steps.gate.outputs.deploy == 'true'
        env:
          APP_NAME: flowsense-api
        run: |
          set -e
          ROUTE=$(cf app "$APP_NAME" | awk '/routes:/{getline; print $1; exit}')
          echo "Route: $ROUTE"
          for i in {1..30}; do
            if curl -sf "https://$ROUTE/health" | tee cf-health.json; then
              exit 0
            fi
            sleep 2
          done
          echo "App not healthy yet"; exit 1

      - name: Upload CF health artifact
        if: steps.gate.outputs.deploy == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cf-health-response
          path: cf-health.json
